[build]
  publish = "nextjs-app/.next"
  command = "cd nextjs-app && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Düz HTML/JS versiyonu için
[context.deploy-preview]
  publish = "plain-html-app"

[context.branch-deploy]
  publish = "plain-html-app"

# Production için Next.js
[context.production]
  publish = "nextjs-app/.next"
  command = "cd nextjs-app && npm install && npm run build" 